// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// CLI operations (migrate, studio, db pull) need a direct, non-pooled
// connection to Neon — the pooled DATABASE_URL is used by PrismaClient
// at runtime via the Neon driver adapter instead (see src/db.ts).
//
// Read via `process.env` (not the strict `env()` helper) because this file
// is loaded for every Prisma command, including `generate`, which doesn't
// touch the database and shouldn't require the variable to be set (e.g. in CI).
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL_UNPOOLED,
  },
});
