// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// CLI operations (migrate, studio, db pull) need a direct, non-pooled
// connection to Neon — the pooled DATABASE_URL is used by PrismaClient
// at runtime via the Neon driver adapter instead (see src/db.ts).
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL_UNPOOLED"),
  },
});
